DROP DATABASE prueba;
CREATE DATABASE prueba;
USE prueba;

CREATE TABLE PLANTAS (
    ID_Planta BIGINT AUTO_INCREMENT PRIMARY KEY,
    Nombrep VARCHAR(50) NOT NULL,
    Nombre_cientifico VARCHAR(70) NOT NULL
);

CREATE TABLE DETALLE_ADMINISTRADOR (
    ID_DetAdm BIGINT AUTO_INCREMENT PRIMARY KEY,
    FKID_ADMIN BIGINT NOT NULL,
    FKID_Planta BIGINT NOT NULL
);

ALTER TABLE DETALLE_ADMINISTRADOR ADD CONSTRAINT Fk_detad_P foreign key(FKID_Planta)
REFERENCES PLANTAS (ID_Planta);

CREATE TABLE ADMINISTRADOR (
    ID_ADMIN BIGINT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100),
    email VARCHAR(100),
    DNI BIGINT NOT NULL
);
ALTER TABLE DETALLE_ADMINISTRADOR ADD CONSTRAINT Fk_detad_adm foreign key(FKID_ADMIN)
REFERENCES ADMINISTRADOR (ID_ADMIN);

CREATE TABLE DETALLE_VISITANTE (
    ID_DetVisit BIGINT AUTO_INCREMENT PRIMARY KEY,
    FKID_Planta BIGINT NOT NULL,
    FKID_Visit BIGINT NOT NULL
);

ALTER TABLE DETALLE_VISITANTE ADD CONSTRAINT Fk_detvis_Usu foreign key(FKID_Planta)
REFERENCES PLANTAS (ID_Planta);

CREATE TABLE VISITANTE (
    ID_VISIT BIGINT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100),
    DNI BIGINT NOT NULL
);
ALTER TABLE DETALLE_VISITANTE ADD CONSTRAINT Fk_detVis_Vis foreign key(FKID_Visit)
REFERENCES VISITANTE (ID_VISIT);

CREATE TABLE INVESTIGACION (
    ID_Inv BIGINT AUTO_INCREMENT PRIMARY KEY,
    Autor VARCHAR (100),
    Titulo VARCHAR (100),
    Contenido TEXT,
    FKID_Investigador BIGINT NOT NULL,
    FKID_Planta BIGINT NOT NULL
);

ALTER TABLE INVESTIGACION ADD CONSTRAINT Fk_IN_U foreign key(FKID_Planta)
REFERENCES PLANTAS (ID_Planta);

CREATE TABLE INVESTIGADORES (
    ID_Inv BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    dni BIGINT not null,
    email VARCHAR(100),
    area_especializacion VARCHAR(100),
    pais VARCHAR(50)
);

ALTER TABLE INVESTIGACION ADD CONSTRAINT Fk_DIN_INV foreign key(FKID_Investigador)
REFERENCES INVESTIGADORES (ID_Inv);

CREATE TABLE IMAGEN (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    FKID_Planta BIGINT NOT NULL,
    direccion VARCHAR(255)
);

ALTER TABLE IMAGEN ADD CONSTRAINT Fk_plan_ima foreign key(FKID_Planta)
REFERENCES PLANTAS (ID_Planta);

CREATE TABLE DETALLE_REGION (
    ID_DetReg BIGINT AUTO_INCREMENT PRIMARY KEY,
    FKID_Planta BIGINT NOT NULL,
    FKID_Reg BIGINT NOT NULL
);

ALTER TABLE DETALLE_REGION ADD CONSTRAINT Fk_plan_DETR foreign key(FKID_Planta)
REFERENCES PLANTAS (ID_Planta);

CREATE TABLE REGION (
    ID_Reg BIGINT AUTO_INCREMENT PRIMARY KEY, 
    Nombre VARCHAR(100),
    Ciudad VARCHAR(100)
);

ALTER TABLE DETALLE_REGION ADD CONSTRAINT Fk_DR_R foreign key(FKID_Reg)
REFERENCES REGION (ID_Reg);

CREATE TABLE DETALLE_CLIMA (
    ID_DetClim BIGINT AUTO_INCREMENT PRIMARY KEY,
    FKID_Clim BIGINT NOT NULL,
    FKID_Reg BIGINT NOT NULL
);
ALTER TABLE DETALLE_CLIMA ADD CONSTRAINT Fk_R_DC foreign key(FKID_Reg)
REFERENCES REGION (ID_Reg);

CREATE TABLE CLIMA (
    ID_Clim BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombrec VARCHAR(100),
    descripcionc TEXT,
    temperatura_promedio DECIMAL(5, 2),
    humedad_promedio DECIMAL(5, 2)
);
ALTER TABLE DETALLE_CLIMA ADD CONSTRAINT Fk_DC_CL foreign key(FKID_Clim)
REFERENCES CLIMA (ID_Clim);

CREATE TABLE DETALLE_SUELO (
    ID_DetSue BIGINT AUTO_INCREMENT PRIMARY KEY,
    FKID_Suelo BIGINT NOT NULL,
    FKID_Reg BIGINT NOT NULL
);
ALTER TABLE DETALLE_SUELO ADD CONSTRAINT Fk_Ds_R foreign key(FKID_Reg)
REFERENCES REGION (ID_Reg);

CREATE TABLE SUELO (
    ID_Suelo BIGINT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100),
    Descripcions TEXT
);
ALTER TABLE DETALLE_SUELO ADD CONSTRAINT Fk_Ds_s foreign key(FKID_Suelo)
REFERENCES SUELO (ID_Suelo);

CREATE TABLE DETALLE_CUIDADO (
    ID_DetCuid BIGINT AUTO_INCREMENT PRIMARY KEY,
    FKID_Planta BIGINT NOT NULL,
    FKID_cuida BIGINT NOT NULL
);

ALTER TABLE DETALLE_CUIDADO ADD CONSTRAINT Fk_p_Dc foreign key(FKID_Planta)
REFERENCES PLANTAS (ID_Planta);

CREATE TABLE CUIDADOS (
    ID_cuida BIGINT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100),
    tipo_cuidado VARCHAR(100),
    INFORMACION TEXT
);

ALTER TABLE DETALLE_CUIDADO ADD CONSTRAINT Fk_DC_C foreign key(FKID_cuida)
REFERENCES CUIDADOS (ID_cuida);


CREATE TABLE DETALLE_PLAGAS (
    ID_DetPla BIGINT AUTO_INCREMENT PRIMARY KEY,
    FKID_Planta BIGINT NOT NULL,
    FKID_PLAG BIGINT NOT NULL
);

ALTER TABLE DETALLE_PLAGAS ADD CONSTRAINT Fk_DP_P foreign key(FKID_Planta)
REFERENCES PLANTAS (ID_Planta);

CREATE TABLE PLAGAS (
    ID_PLAG BIGINT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100),
    TIPO VARCHAR(100),
    Descripcion TEXT
);

ALTER TABLE DETALLE_PLAGAS ADD CONSTRAINT Fk_DP_PL foreign key(FKID_PLAG)
REFERENCES PLAGAS (ID_PLAG);

CREATE TABLE DETALLE_LOCALIZACION (
    ID_DetLoc BIGINT AUTO_INCREMENT PRIMARY KEY,
    FKID_Planta BIGINT NOT NULL,
    FKID_LOCALI BIGINT NOT NULL
);
ALTER TABLE DETALLE_LOCALIZACION ADD CONSTRAINT Fk_p_dl foreign key(FKID_Planta)
REFERENCES PLANTAS (ID_Planta);

CREATE TABLE LOCALIZACION (
    ID_LOCALI BIGINT AUTO_INCREMENT PRIMARY KEY,
    FKID_DetJBot BIGINT,
    FKID_DetZon BIGINT ,
    FKID_DetPin BIGINT ,
    Nombre VARCHAR(100),
    Ciudad VARCHAR(100),
    Direccion VARCHAR(100)
);

ALTER TABLE DETALLE_LOCALIZACION ADD CONSTRAINT Fk_DL_L foreign key(FKID_LOCALI)
REFERENCES LOCALIZACION (ID_LOCALI);

CREATE TABLE DETALLE_JBOTANICO (
    ID_DetJBot BIGINT AUTO_INCREMENT PRIMARY KEY,
    FKID_JBot BIGINT NOT NULL,
    FKID_LOCALI BIGINT NOT NULL
);

ALTER TABLE DETALLE_JBOTANICO ADD CONSTRAINT Fk_L_DJB foreign key(FKID_LOCALI)
REFERENCES LOCALIZACION (ID_LOCALI);

CREATE TABLE JARDIN_BOTANICO (
    ID_JBot BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombrep VARCHAR(100),
    nombrej VARCHAR(100),
    ubicacion VARCHAR(255),
    descripcion TEXT,
    superficie DECIMAL(10, 2),
    fecha_creacion DATE
);

ALTER TABLE DETALLE_JBOTANICO ADD CONSTRAINT Fk_DJB_JB foreign key(FKID_JBot)
REFERENCES JARDIN_BOTANICO (ID_JBot);

CREATE TABLE DETALLE_ZONA (
    ID_DetZon BIGINT AUTO_INCREMENT PRIMARY KEY,
    FKID_ZRes BIGINT NOT NULL,
    FKID_LOCALI BIGINT NOT NULL
);

ALTER TABLE DETALLE_ZONA ADD CONSTRAINT Fk_L_DZ foreign key(FKID_LOCALI)
REFERENCES LOCALIZACION (ID_LOCALI);

CREATE TABLE ZONA_RESERVA (
    ID_ZRes BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombrep VARCHAR(100),
    nombrez VARCHAR(100)
);

ALTER TABLE DETALLE_ZONA ADD CONSTRAINT Fk_DZ_ZR foreign key(FKID_ZRes)
REFERENCES ZONA_RESERVA (ID_ZRes);

CREATE TABLE DETALLE_PINES (
    ID_DetPin BIGINT AUTO_INCREMENT PRIMARY KEY,
    FKID_Pin BIGINT NOT NULL,
    FKID_LOCALI BIGINT NOT NULL
);

ALTER TABLE DETALLE_PINES ADD CONSTRAINT Fk_L_DPI foreign key(FKID_LOCALI)
REFERENCES LOCALIZACION (ID_LOCALI);

CREATE TABLE PINES (
    ID_Pin BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    latitud DOUBLE,
    longitud DOUBLE
);
ALTER TABLE DETALLE_PINES ADD CONSTRAINT Fk_DPI_PI foreign key(FKID_Pin)
REFERENCES PINES (ID_Pin);

CREATE TABLE DETALLE_FLORACION (
    ID_DetFlo BIGINT AUTO_INCREMENT PRIMARY KEY,
    FKID_Planta BIGINT NOT NULL,
    FKID_Flora BIGINT NOT NULL
);
ALTER TABLE DETALLE_FLORACION ADD CONSTRAINT Fk_p_Df foreign key(FKID_Planta)
REFERENCES PLANTAS (ID_Planta);

CREATE TABLE FLORACION (
    ID_Flora BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    inicio_flora VARCHAR(100),
    fin_flora VARCHAR(100)
);

ALTER TABLE DETALLE_FLORACION ADD CONSTRAINT Fk_DF_F foreign key(FKID_Flora)
REFERENCES FLORACION (ID_Flora);

CREATE TABLE DETALLE_TAXONOMIA (
    ID_DetTaxo BIGINT AUTO_INCREMENT PRIMARY KEY,
    FKID_Planta BIGINT NOT NULL,
    FKID_Taxo BIGINT NOT NULL
);

ALTER TABLE DETALLE_TAXONOMIA ADD CONSTRAINT Fk_p_Dt foreign key(FKID_Planta)
REFERENCES PLANTAS (ID_Planta);

CREATE TABLE TAXONOMIA (
    ID_Taxo BIGINT AUTO_INCREMENT PRIMARY KEY,
    FKID_Planta BIGINT NOT NULL,
    nombre VARCHAR(100),
    reino VARCHAR(50),
    division VARCHAR(50),
    subdivision VARCHAR(50),
    clase VARCHAR(50),
    subclase VARCHAR(50),
    orden VARCHAR(50),
    familia VARCHAR(50),
    genero VARCHAR(50),
    especie VARCHAR(50)
);

ALTER TABLE DETALLE_TAXONOMIA ADD CONSTRAINT Fk_DT_T foreign key(FKID_Taxo)
REFERENCES TAXONOMIA (ID_Taxo);


-------------------------------------------------------------------------------Inserciones de usuarios

INSERT INTO ADMINISTRADOR (Nombre, email, DNI) VALUES 
('Laura Martínez', 'laura.martinez@empresa.com', 12345678),
('Carlos Gómez', 'carlos.gomez@empresa.com', 87654321),
('Ana Torres', 'ana.torres@empresa.com', 11223344);


INSERT INTO INVESTIGADORES (nombre, dni, email, area_especializacion, pais) VALUES 
('Luis Fernandez', 12345679, 'luis.fernandez@universidad.com', 'Agroecologo', 'Espana'),
('Marta Lopez', 98765432, 'marta.lopez@investigacion.org', 'Botanica Sistematica', 'Mexico'),
('Ricardo Perez', 55667788, 'ricardo.perez@instituto.com', 'Fisiologo Vegetal', 'Argentina');
